<a href="https://colab.research.google.com/github/RiazullJannat/DL/blob/main/backProp_using_pitroch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
data = torch.tensor(
    [
        [2,3,4],
        [5,6,7],
        [8,9,10]
    ]
)
data

tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])

In [3]:
x = data[:,:2].float()
x

tensor([[2., 3.],
        [5., 6.],
        [8., 9.]])

In [4]:
y = data[:,-1].float()
y

tensor([ 4.,  7., 10.])

In [5]:
def initialize_parameters():
  parameters = {}
  parameters["w1"] = torch.ones((2,2)) * 0.1
  parameters['b1'] = torch.zeros((2,1))

  parameters['W2'] = torch.ones( (2,1) ) * 0.1

  parameters['b2'] = torch.zeros( (1,1) )
  return parameters

In [6]:
initialize_parameters()

{'w1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'W2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

Creating Tensors


In [7]:
print("torch version--->>", torch.__version__)

torch version--->> 2.11.0+cpu


In [8]:
if torch.cuda.is_available():
  print("GPU is available.")
  print(f"Device name {torch.cuda.get_device_name(0)}")
else:
  print("No GPU is available...")

No GPU is available...


In [9]:
a = torch.empty(2,3)
a

tensor([[5.9479e-21, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.5399e-41]])

In [10]:
type(a)

torch.Tensor

In [11]:
b = torch.zeros(2,4)
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
c = torch.ones(2,4)
c

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
d = torch.rand(2,4)
d

tensor([[0.0460, 0.1389, 0.5696, 0.7672],
        [0.2039, 0.9790, 0.3791, 0.1013]])

In [14]:
torch.manual_seed(100)
torch.rand(2,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

In [15]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
torch.arange(0,10,1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
torch.linspace(1,10,100)

tensor([ 1.0000,  1.0909,  1.1818,  1.2727,  1.3636,  1.4545,  1.5455,  1.6364,
         1.7273,  1.8182,  1.9091,  2.0000,  2.0909,  2.1818,  2.2727,  2.3636,
         2.4545,  2.5455,  2.6364,  2.7273,  2.8182,  2.9091,  3.0000,  3.0909,
         3.1818,  3.2727,  3.3636,  3.4545,  3.5455,  3.6364,  3.7273,  3.8182,
         3.9091,  4.0000,  4.0909,  4.1818,  4.2727,  4.3636,  4.4545,  4.5455,
         4.6364,  4.7273,  4.8182,  4.9091,  5.0000,  5.0909,  5.1818,  5.2727,
         5.3636,  5.4545,  5.5455,  5.6364,  5.7273,  5.8182,  5.9091,  6.0000,
         6.0909,  6.1818,  6.2727,  6.3636,  6.4545,  6.5455,  6.6364,  6.7273,
         6.8182,  6.9091,  7.0000,  7.0909,  7.1818,  7.2727,  7.3636,  7.4545,
         7.5455,  7.6364,  7.7273,  7.8182,  7.9091,  8.0000,  8.0909,  8.1818,
         8.2727,  8.3636,  8.4545,  8.5455,  8.6364,  8.7273,  8.8182,  8.9091,
         9.0000,  9.0909,  9.1818,  9.2727,  9.3636,  9.4545,  9.5455,  9.6364,
         9.7273,  9.8182,  9.9091, 10.00

Tensors Shape

In [19]:
torch.manual_seed(100)
x = torch.rand(2,2)
print(x)
# x.shape
y = torch.empty_like(x)
y

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])


tensor([[6.0189e-21, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])

In [20]:
z = torch.ones_like(y)
z

tensor([[1., 1.],
        [1., 1.]])

In [21]:
r = torch.rand_like(z)
r

tensor([[0.6765, 0.7539],
        [0.2627, 0.0428]])

Data Type

In [22]:
r.dtype

torch.float32

In [23]:
x =torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)
x

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
x.dtype

torch.int32

In [25]:
x = x.to(torch.float32)
x.dtype

torch.float32

Mathematical Operation

In [26]:
print(x+2)

tensor([3., 4., 5.])


Reduction Operation

In [27]:
e = torch.randint(size=(2,3), low = 0, high= 10, dtype=torch.float32)
e

tensor([[8., 0., 4.],
        [3., 8., 8.]])

In [28]:
torch.sum(e)

tensor(31.)

In [29]:
torch.sum(e, dim=0)

tensor([11.,  8., 12.])

In [30]:
torch.mean(e)

tensor(5.1667)

In [31]:
torch.mean(e,dim=1)

tensor([4.0000, 6.3333])

In [32]:
torch.median(e)

tensor(4.)

In [33]:
torch.max(e)

tensor(8.)

In [34]:
torch.min(e)

tensor(0.)

In [35]:
torch.prod(e, dim=0)

tensor([24.,  0., 32.])

Transpose

In [36]:
f = torch.randint(size=(2,3),low = 0,high = 10)
g = torch.randint(size=(3,2),low = 0, high = 10)
h = torch.randint(size=(3,3),low = 0,high = 10, dtype=torch.float32)

In [37]:
torch.matmul(g,f)

tensor([[32, 60, 29],
        [16, 40, 22],
        [ 0,  4,  3]])

In [38]:
f.shape

torch.Size([2, 3])

In [39]:
f=torch.transpose(f,0,1)

In [40]:
f

tensor([[4, 0],
        [4, 4],
        [1, 3]])

In [41]:
torch.det(h)

tensor(315.)

Copying a tensor

In [47]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [48]:
b= a
b
b[2] = 30
b

[1, 2, 30, 4, 5]

In [49]:
a

[1, 2, 30, 4, 5]

In [53]:
a = torch.tensor([1,2,3,4,5])
a

tensor([1, 2, 3, 4, 5])

In [55]:
b = a.clone()
b

tensor([1, 2, 3, 4, 5])