<a href="https://colab.research.google.com/github/RiazullJannat/DL/blob/main/backpropagation_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

data = torch.tensor(
    [
        [2,3,3],
        [5,6,4],
        [7,8,5]

    ]
)
data

tensor([[2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]])

In [3]:
x = data[:,0:2]
y = data[:,-1]

In [4]:
x

tensor([[2, 3],
        [5, 6],
        [7, 8]])

In [5]:
y

tensor([3, 4, 5])

**Weight Initialization**

In [8]:
# w=1, b = 0

def initialize_parameters():
  parameters = {}
  parameters["w1"] = torch.ones((2,2)) * 0.1
  parameters["b1"] = torch.ones((2,1))

  parameters["w2"] = torch.ones((2,1)) * 0.1
  parameters["b2"] = torch.zeros((1,1))

  return parameters

In [9]:
initialize_parameters()

{'w1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[1.],
         [1.]]),
 'w2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

**Batter way**

In [12]:
def initialize_parameters2(layer_dims):
  torch.manual_seed(3)
  parameters = {}
  L = len(layer_dims)

  for i in range(1,L):
    parameters["w"+str(i)] = torch.ones((layer_dims[i-1], layer_dims[i])) * 0.1
    parameters["b"+str(i)] = torch.zeros((layer_dims[i], 1))

  return parameters


In [13]:
initialize_parameters2([2,2,1])

{'w1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'w2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

**Forward Propagation**

In [14]:
def liner_forward(a_prev, w, b):
  z = torch.matmul(w.T, a_prev) + b
  return z

In [16]:
def l_layer_forward(x, parameters):
  a = x
  l = len(parameters)//2
  for i in range(1,l+1):
    a_prev = a

    wl = parameters['w' + str(i)]
    bl = parameters['b' + str(i)]

    a = liner_forward(a_prev, wl, bl)
  return a, a_prev

In [15]:
params = initialize_parameters2([2, 2, 1])
params

{'w1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'w2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

In [18]:
X_sample= x[0].reshape(2,1).float() # Convert X_sample to float
y_hat, a1 = l_layer_forward(X_sample, params)
print("y hat->> ", y_hat)
print(a1)

y hat->>  tensor([[0.1000]])
tensor([[0.5000],
        [0.5000]])


In [19]:
print("loss-->> ", (y - y_hat)**2)

loss-->>  tensor([[ 8.4100, 15.2100, 24.0100]])
